# Site settings
title: Hendrik's Blog
email: 321hendrik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes on working as a Systems Developer (App, Web, Server)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hendrikelsner.github.io" # the base hostname & protocol for your site
github_username:  hendrikelsner

# Build settings
include: [img]
markdown: kramdown
